### ISSUE TITLE
Week 2 In-Class: Consider reducing complexity

### ISSUE THREAD

**Issue by daniellemccool** [kylelang/tcsm#11]
https://github.com/kylelang/tcsm/blame/89c7e64e7e8cd3dad803a36b45d0ea7a06e0d20d/sections/week2/class.Rmd#L786-L790

Using multiple pipes and mutate may be a bit much to follow here, although I recognize they can just copy-paste here.

`
mod <- 'RT ~ 1 + HH + HF'

lavOut <- drivers %>%
  mutate(HH = ifelse(condition == "hand-held", 1, 0), # Create dummy code for "hand-held" condition
         HF = ifelse(condition == "hands-free", 1, 0) # Create dummy code for "hands-free" condition
         ) %>%
  sem(mod, data = .) # Estimate the model

summary(lavOut)
`

**Comment by kylelang** [comment]
This issue should be resolved by #12.
